#!/bin/bash

# Set our shell to use emacs key bindings, not motherfucking vim.
set -o emacs

# This is my machine
export HOSTNAME=bpf

### Aliases!

alias ls="ls -F"
alias rm="rm -i"

alias gs='git status'
alias gp='git pull --rebase'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gl='git log --stat'

alias lumber='cd ~/lumber/code'
alias lumberweb='cd ~/lumber/code/www && workon wwwlumber'

### Path!

#export PATH=.:/usr/local/sbin:/usr/local/bin:~/bin:$PATH
export PATH=/usr/local/apache2/bin:/usr/local/mysql/bin:$PATH
export PATH=/Applications/eclipse:$PATH
export PATH=.:~/bin:/usr/local/bin:/usr/local/sbin:/usr/local/Cellar/ruby/1.8.7-p249/bin:$PATH

# Java!

export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home

# Editor!

#export EDITOR="mvim -f"
export EDITOR="subl -w"

### Terminal stuff!

export TERM=xterm-color
export CLICOLOR="true"
export LSCOLORS="exfxcxdxbxegedabagacad"

### QT blargh

export QMAKESPEC="macx-g++"

### Build against MySQL libraries!

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/mysql/lib/

### Node

export NODE_PATH=/usr/local/lib/node

# RVM stuff
if [[ -s "$HOME/.rvm/scripts/rvm" ]]  ; then source "$HOME/.rvm/scripts/rvm" ; fi



### Python 2.6.5 + Virtualenv!

export PATH=/usr/local/share/python:/usr/local/Cellar/python2.6/2.6.5/bin:/usr/local/Cellar/python/2.7.1/bin:$PATH
source /usr/local/share/python/virtualenvwrapper.sh
export PYTHONPATH=:

export PIP_DOWNLOAD_CACHE=$HOME/.pip-download-cache/

### CUDA

export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

### TextMate bits and pieces

export TM_PYCHECKER=/usr/local/share/python/pyflakes
export TM_RST2HTML="/usr/local/Cellar/python2.6/2.6.5/bin/python /usr/local/Cellar/python2.6/2.6.5/bin/rst2html.py"

### Android Development
export ANDROID_SDK=/Developer/Android/android-sdk-macosx
export ANDROID_NDK=/Developer/Android/android-ndk-r7
export PATH=$ANDROID_SDK/tools:$ANDROID_SDK/platform-tools:$ANDROID_NDK:$PATH
export PATH=~/lumber/code/android/bin:$PATH

### C/C++

export CMAKE_C_COMPILER_ENV_VAR=CC
export CMAKE_CXX_COMPILER_ENV_VAR=CXX

### git sweetness, with branch in the prompt

source ~/.git-completion.sh

# Set the base PS1
# PS1="\u:\h \W$ "
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " \[\033[01;35m\](%s)\[\033[0m\]")$ '
export GIT_PS1_SHOWDIRTYSTATE=1

# Hub
eval "$(hub alias -s)"
#source ~/.hub.bash_completion.sh

workon home || mkvirtualenv home && workon home



# Gist
export GITHUB_USER="burnto"

