#!/bin/bash

# Set our shell to use emacs key bindings
set -o emacs

### Aliases!
alias ls="ls -F"
alias rm="rm -i"

alias gs='git status'
alias gp='git pull --rebase'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gl='git log --stat'

### Path!
export PATH="/usr/local/apache2/bin:$PATH"
export PATH="/Applications/eclipse:$PATH"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export PATH=".:$HOME/bin:$PATH"

# Java!
export JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Home"

# Editor!
#export EDITOR="mvim -f"
#export EDITOR="subl -w"
export EDITOR='mvim -f --nomru -c "au VimLeave * !open -a Terminal"'

### Terminal stuff!

export TERM=xterm-color
export CLICOLOR="true"
export LSCOLORS="exfxcxdxbxegedabagacad"

### QT blargh
export QMAKESPEC="macx-g++"

### Build against MySQL libraries!
export PATH="/usr/local/mysql/bin:$PATH"
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/usr/local/mysql/lib"

### Python 2.6.5 + Virtualenv!
export PATH=/usr/local/share/python:/usr/local/Cellar/python2.6/2.6.5/bin:/usr/local/Cellar/python/2.7.1/bin:$PATH
source /usr/local/bin/virtualenvwrapper.sh > /dev/null 2>&1 || source /usr/local/Cellar/python2.6/2.6.5/bin/virtualenvwrapper.sh > /dev/null 2>&1
export PYTHONPATH=:/usr/local/lib/python2.6/site-packages:$PYTHONPATH
export PIP_DOWNLOAD_CACHE=$HOME/.pip-download-cache/

### CUDA

export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

### TextMate bits and pieces

export TM_PYCHECKER=/usr/local/share/python/pyflakes
export TM_RST2HTML="/usr/local/Cellar/python2.6/2.6.5/bin/python /usr/local/Cellar/python2.6/2.6.5/bin/rst2html.py"

### Android Development
export ANDROID_HOME="$HOME/android/adt-bundle-mac-x86_64-20130219/sdk"
export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"

### C/C++

export CMAKE_C_COMPILER_ENV_VAR=CC
export CMAKE_CXX_COMPILER_ENV_VAR=CXX

### git sweetness, with branch in the prompt
source ~/.git-completion.sh

# Set the base PS1
# PS1="\u:\h \W$ "
PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " \[\033[01;35m\](%s)\[\033[0m\]")$ '
export GIT_PS1_SHOWDIRTYSTATE=1

# Hub
eval "$(hub alias -s)"
#source ~/.hub.bash_completion.sh

# workon home || mkvirtualenv home && workon home

# Github/Gist
export GITHUB_USER="burnto"

# Go
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$PATH

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

### Node
export NODE_PATH=/usr/local/lib/node
export PATH="/usr/local/share/npm/bin:$PATH"

# autoenv
# https://github.com/kennethreitz/autoenv
source /usr/local/opt/autoenv/activate.sh
